title: Home
views:
  - cards:
      - hold_action:
          action: none
        type: entity-button
        theme: Backend-selected
        tap_action:
          action: toggle
        entity: lock.schlage_be469_touchscreen_deadbolt_locked
        name: FRONT DOOR
      - entity: weather.dark_sky
        type: weather-forecast
        name: Weather
      - type: gauge
        min: 0
        max: 100
        severity:
          green: 75
          yellow: 35
          red: 10
        theme: Backend-selected
        entity: sensor.frontdoor_battery
        unit: '%'
        name: FRONT DOOR BATTERY
    badges: []
    path: default_view
    title: Home
    panel: false
  - panel: true
    badges: []
    cards: []
    title: Front Door
    icon: door

